---
- name: Initialize - Map users_profiles definitions to system_users objects
  set_fact:
    register_system_user:
      name: "{{ item.name }}"
      append: "{{ item.append|d(omit) }}"
      comment: "{{ item.comment|d(omit) }}"
      createhome: "{{ item.createhome|d(omit) }}"
      expires: "{{ item.expires|d(omit) }}"
      generate_ssh_key: "{{ item.generate_ssh_key|d(omit) }}"
      group: "{{ item.group|d(omit) }}"
      groups: "{{ item.groups|d(None) }}"
      home: "{{ item.home|d(omit) }}"
      home_group: "{{ item.home_group|d(omit) }}"
      home_mode: "{{ item.home_mode|d(omit) }}"
      home_owner: "{{ item.home_owner|d(omit) }}"
      move_home: "{{ item.move_home|d(omit) }}"
      password: "{{ item.password|d(omit) }}"
      remove: "{{ item.remove|d(omit) }}"
      shell: "{{ item.shell|d(omit) }}"
      skeleton: "{{ item.skeleton|d(omit) }}"
      ssh_key_bits: "{{ item.ssh_key_bits|d(omit) }}"
      ssh_key_comment: "{{ item.ssh_key_comment|d(omit) }}"
      ssh_key_file: "{{ item.ssh_key_file|d(omit) }}"
      ssh_key_passphrase: "{{ item.ssh_key_passphrase|d(omit) }}"
      ssh_key_type: "{{ item.ssh_key_type|d(omit) }}"
      system: "{{ item.system|d(omit) }}"
      uid: "{{ item.uid|d(omit) }}"
      update_password: "{{ item.update_password|d(omit) }}"
      disabled: "{{ item.disabled|d(false) }}"
  with_items:
    - "{{ users_profiles__list }}"
  register: "users_profiles__register_mapped"
  when: (item.name is defined and item.name|trim)

- name: Initialize - Map users_profiles definitions to system_users objects
  set_fact:
    users_profiles__register_system_users: "{{ users_profiles__register_mapped.results
                                                  |selectattr('ansible_facts', 'defined')|list
                                                  |map(attribute='ansible_facts.register_system_user')|list }}"
